// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0JSlHr0BKRIaPZH1bbZyvKqIz7Q89j0',
    appId: '1:788225847964:web:5843576ec2f37ef659b359',
    messagingSenderId: '788225847964',
    projectId: 'online-shopping-app-2e14e',
    authDomain: 'online-shopping-app-2e14e.firebaseapp.com',
    storageBucket: 'online-shopping-app-2e14e.firebasestorage.app',
    measurementId: 'G-RWKWGPC9DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8FtHN764A7HdbDj8OX7BsuRKh3hyCaNk',
    appId: '1:788225847964:android:16f400272e2e674459b359',
    messagingSenderId: '788225847964',
    projectId: 'online-shopping-app-2e14e',
    storageBucket: 'online-shopping-app-2e14e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJ7VSOpeuGN6oOaOD7q0V05ZyC6TPKCc',
    appId: '1:788225847964:ios:5a729e7ad2da1b6b59b359',
    messagingSenderId: '788225847964',
    projectId: 'online-shopping-app-2e14e',
    storageBucket: 'online-shopping-app-2e14e.firebasestorage.app',
    iosBundleId: 'com.example.onlineShoppingApp',
  );
}
